#!/bin/zsh
# Stage the shared extension source into build/<target> with the right manifest
# and native-helper id baked in.
#
#   ./scripts/stage.sh safari|chrome
set -euo pipefail
ROOT="${0:A:h}/.."
TARGET="${1:-}"

case "$TARGET" in
  safari) NATIVE_ID="com.yinka.NewsOpen.Extension" ;;
  chrome) NATIVE_ID="com.yinka.newsopen" ;;
  *) echo "usage: stage.sh safari|chrome" >&2; exit 2 ;;
esac

OUT="$ROOT/build/$TARGET/extension"
rm -rf "$OUT"
mkdir -p "$OUT"

cp -R "$ROOT/extension/icons" "$OUT/icons"
cp "$ROOT/extension/background.js" "$ROOT/extension/publishers.js" \
   "$ROOT/extension/popup.html" "$ROOT/extension/popup.js" \
   "$ROOT/extension/options.html" "$ROOT/extension/options.js" "$OUT/"
cp "$ROOT/extension/manifest.$TARGET.json" "$OUT/manifest.json"
[[ "$TARGET" == "chrome" ]] && cp "$ROOT/extension/sw.js" "$OUT/"

cat > "$OUT/target.js" <<TARGETJS
/* Generated by scripts/stage.sh — do not edit. */
self.TARGET = '$TARGET';
self.NATIVE_APP_ID = '$NATIVE_ID';
TARGETJS

echo "staged $TARGET -> $OUT"
